import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/shared/styles/globals.scss";
import { Toaster } from "react-hot-toast";
import { toastStyle } from "@/shared/styles/toastStyle";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Toaster toastOptions={toastStyle} containerStyle={{ top: 100 }} />
        {children}
      </body>
    </html>
  );
}
