import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/shared/styles/globals.css";
import { Toaster } from "react-hot-toast";
import { toastStyle } from "@/shared/styles/toastStyle";
import Header from "@/features/landing-page/components/Header";
import Footer from "@/features/landing-page/components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster toastOptions={toastStyle} containerStyle={{ top: 100 }} />
        <div className="xl:w-[90%] w-full m-auto px-4">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
